<?php


namespace MonsterMQ\Interfaces\AMQPDispatchers;


use MonsterMQ\Exceptions\ConnectionException;
use MonsterMQ\Exceptions\ProtocolException;

interface BasicDispatcher
{
    /**
     * This method requests a specific quality of service. The QoS can be
     * specified for the current channel or for all channels on the connection.
     *
     * @param int  $channel       Channel going to be used for setting up quality
     *                            of service.
     * @param int  $prefetchSize  Size of message which may be sent in advance.
     * @param int  $prefetchCount Number of messages which may be sent in advance.
     * @param bool $global        False enables qos per consumer. True - per connection.
     */
    public function sendQos(int $channel, int $prefetchSize = 0, int $prefetchCount = 0, bool $global = false);

    /**
     * This method tells the client that the requested QoS levels could be handled
     * by the server. The requested QoS applies to all active consumers until
     * a new QoS is defined.
     *
     * @throws ProtocolException
     * @throws \MonsterMQ\Exceptions\SessionException
     */
    public function receiveQosOk();

    /**
     * This method asks the server to start a "consumer", which is a transient
     * request for messages from a specific queue. Consumers last as long as
     * the channel they were declared on, or until the client cancels them.
     *
     * @param int    $channel     Channel which going to be used.
     * @param string $queueName   Queue to consume.
     * @param string $consumerTag The identifier of the consumer.
     * @param bool   $noLocal     If the no-local field is set the server will
     *                            not send messages to the connection that
     *                            published them.
     * @param bool   $noAck       If this field is set the server does not
     *                            expect acknowledgements for messages. That
     *                            is, when a message is delivered to the client
     *                            the server assumes the delivery will succeed
     *                            and immediately dequeues it.
     * @param bool   $exclusive   Request exclusive consumer access, meaning
     *                            only this consumer can access the queue.
     * @param bool   $noWait      Whether the server will respond with Consume-Ok
     * @param array  $arguments   A set of arguments for the consume. The syntax
     *                            and semantics of these arguments depends on the
     *                            server implementation.
     */
    public function sendConsume(
        int $channel,
        string $queueName,
        string $consumerTag,
        bool $noLocal = false,
        bool $noAck = false,
        bool $exclusive = false,
        bool $noWait = false,
        array $arguments = []
    );

    /**
     * Confirm a new consumer.
     *
     * @return string $consumerTag The identifier of consumer which may be
     *                             specified by client or generated by server.
     *
     * @throws ProtocolException
     * @throws \MonsterMQ\Exceptions\SessionException
     */
    public function receiveConsumeOk();

    /**
     * End a queue consumer.
     *
     * @param int    $channel     Channel going to be used.
     * @param string $consumerTag Consumer tag that indicates which consumer
     *                            will be ended.
     * @param bool   $noWait      Whether the server will respond with Cancel-Ok.
     */
    public function sendCancel(int $channel, string $consumerTag, bool $noWait = false);

    /**
     * This method confirms that the cancellation was completed.
     *
     * @return string $consumerTag Identifier of consumer which was canceled.
     *
     * @throws ProtocolException
     * @throws \MonsterMQ\Exceptions\SessionException
     */
    public function receiveCancelOk();

    /**
     * This method publishes a message to a specific exchange. The message will
     * be routed to queues as defined by the exchange configuration and
     * distributed to any active consumers when the transaction, if any, is
     * committed.
     *
     * @param int    $channel      Channel going to be used.
     * @param string $exchangeName Exchange going to be used for publishing.
     * @param string $routingKey   Routing key for publishing.
     * @param bool   $mandatory    This flag tells the server how to react if
     *                             the message cannot be routed to a queue. If
     *                             this flag is set, the server will return an
     *                             unroutable message with a Return method. If
     *                             this flag is zero, the server silently drops
     *                             the message.
     * @param bool   $immediate    This flag tells the server how to react if
     *                             the message cannot be routed to a queue
     *                             consumer immediately. If this flag is set,
     *                             the server will return an undeliverable
     *                             message with a Return method. If this flag
     *                             is zero, the server will queue the message,
     *                             but with no guarantee that it will ever be
     *                             consumed.
     */
    public function sendPublish(
        int $channel,
        string $routingKey,
        string $exchangeName = "",
        bool $mandatory = false,
        bool $immediate = false
    );

    /**
     * This method returns an undeliverable message that was published with the
     * "immediate" flag set, or an unroutable message published with the
     * "mandatory" flag set. The reply code and text provide information
     * about the reason that the message was undeliverable.
     *
     * @return array Contains reply code, reply text, exchange and routing key
     *               that was used for publishing.
     *
     * @throws ProtocolException
     * @throws \MonsterMQ\Exceptions\SessionException
     * @throws ConnectionException
     */
    public function receiveReturn();

    /**
     * This method provides a direct access to the messages in a queue using a
     * synchronous dialogue that is designed for specific types of application
     * where synchronous functionality is more important than performance.
     *
     * @param int    $channel   Channel going to be used.
     * @param string $queueName Queue to be accessed.
     * @param bool   $noAck     If this field is set the server does not
     *                          expect acknowledgements for messages. That
     *                          is, when a message is delivered to the client
     *                          the server assumes the delivery will succeed
     *                          and immediately dequeues it.
     */
    public function sendGet(int $channel, string $queueName, bool $noAck = false);

    /**
     * Receives response to Get method along with following message.
     *
     * @return array|null Message content with used channel. Or null if requested
     *                    queue is empty.
     *
     * @throws ConnectionException
     * @throws ProtocolException
     * @throws \MonsterMQ\Exceptions\SessionException
     */
    public function receiveGetOkOrGetEmpty();

    /**
     * Acknowledges one or more messages.
     *
     * @param int  $channel  Channel going to be used.
     * @param bool $multiple If set to 1, the delivery tag is treated as
     *                       "up to and including", so that multiple messages
     *                        can be acknowledged with a single method. If set
     *                        to zero, the delivery tag refers to a single
     *                        message. If the multiple field is 1, and the
     *                        delivery tag is zero, this indicates acknowledgement
     *                        of all outstanding messages.
     */
    public function sendAck(int $channel, $deliveryTag = null, bool $multiple = false);

    /**
     * This method allows a client to reject a message. It can be used to
     * interrupt and cancel large incoming messages, or return untreatable
     * messages to their original queue.
     *
     * @param int  $channel Channel going to be used.
     * @param bool $requeue If requeue is true, the server will attempt to
     *                       requeue the message. If requeue is false or the
     *                       requeue attempt fails the messages are discarded
     *                       or dead-lettered.
     */
    public function sendReject(int $channel, bool $multiple = false);

    /**
     * This method asks the server to redeliver all unacknowledged messages
     * on a specified channel. Zero or more messages may be redelivered.
     *
     * @param int $channel  Channel going to be used.
     * @param bool $requeue If this field is zero, the message will be redelivered
     *                      to the original recipient. If this bit is 1, the server
     *                      will attempt to requeue the message, potentially then
     *                      delivering it to an alternative subscriber.
     */
    public function sendRecover(int $channel, bool $requeue = false);

    /**
     * Confirms recovery.
     *
     * @throws ConnectionException
     * @throws ProtocolException
     * @throws \MonsterMQ\Exceptions\SessionException
     */
    public function receiveRecoverOk();

    /**
     * This method allows a client to reject one or more incoming messages. It
     * can be used to interrupt and cancel large incoming messages, or return
     * untreatable messages to their original queue.
     *
     * @param int  $channel     Channel going to be used.
     * @param null $deliveryTag Delivery tag of message.
     * @param bool $multiple    If set to 1, the delivery tag is treated as
     *                          "up to and including", so that multiple messages
     *                          can be rejected with a single method. If set to
     *                          zero, the delivery tag refers to a single message.
     *                          If the multiple field is 1, and the delivery tag
     *                          is zero, this indicates rejection of all
     *                          outstanding messages.
     * @param bool $requeue     If requeue is true, the server will attempt to
     *                          requeue the message. If requeue is false or the
     *                          requeue attempt fails the messages are discarded
     *                          or dead-lettered.
     */
    public function sendNack(int $channel, $deliveryTag = null, bool $multiple = false, bool $requeue = false);
}